/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#4f46e5',
        'on-primary': '#ffffff',
        'primary-container': '#eef2ff',
        'primary-hover': '#4338ca',
        'primary-muted': '#a5b4fc',
        secondary: '#64748b',
        'on-secondary': '#ffffff',
        'secondary-container': '#f1f5f9',
        success: '#10b981',
        'on-success': '#ffffff',
        'success-container': '#d1fae5',
        'success-content': '#065f46',
        warning: '#f59e0b',
        'on-warning': '#ffffff',
        'warning-container': '#fef3c7',
        'warning-content': '#92400e',
        danger: '#ef4444',
        'on-danger': '#ffffff',
        'danger-container': '#fee2e2',
        'danger-content': '#991b1b',
        bg: '#ffffff',
        surface: '#f9fafb',
        border: '#e5e7eb',
        muted: '#6b7280',
        text: '#1f2937',
        heading: '#111827',
        'footer-bg': '#f3f4f6',
        'primary-dark': '#6366f1',
        'on-primary-dark': '#ffffff',
        'primary-container-dark': '#1e1b4b',
        'primary-hover-dark': '#818cf8',
        'secondary-dark': '#94a3b8',
        'on-secondary-dark': '#020617',
        'secondary-container-dark': '#1e293b',
        'success-dark': '#34d399',
        'on-success-dark': '#022c22',
        'success-container-dark': '#064e3b',
        'success-content-dark': '#6ee7b7',
        'warning-dark': '#fbbf24',
        'on-warning-dark': '#451a03',
        'warning-container-dark': '#78350f',
        'warning-content-dark': '#fde68a',
        'danger-dark': '#f87171',
        'on-danger-dark': '#450a0a',
        'danger-container-dark': '#7f1d1d',
        'danger-content-dark': '#fca5a5',
        'bg-dark': '#0f172a',
        'surface-dark': '#1e293b',
        'border-dark': '#334155',
        'muted-dark': '#94a3b8',
        'text-dark': '#e2e8f0',
        'heading-dark': '#f1f5f9',
        'footer-bg-dark': '#0f172a',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
